quarkus:
  datasource:
    username: postgres
    password: postgres
    jdbc:
      url: jdbc:postgresql://localhost:5432/bazar_file

  s3:
    endpoint: http://localhost:9000
    access-key: test
    secret-key: test123
    region: us-east-1

settings:
  s3:
    bucket:
      files: files
    url-ttl: 3600