quarkus:
  datasource:
    username: postgres
    password: postgres
    jdbc:
      url: jdbc:postgresql://localhost:5432/bazar_file

  s3:
    endpoint-override: http://localhost:9000
    path-style-access: true
    aws:
      region: us-east-1
      credentials:
        type: static
        static-provider:
          access-key-id: test
          secret-access-key: test123

settings:
  s3:
    bucket:
      files: files
    upload-url-ttl: 3600
    download-url-ttl: 3600
    internal-endpoint: http://localhost:9000
  scheduler:
    delete-files:
      cron: "10s"
      batch-size: 2

kafka:
  bootstrap:
    servers: localhost:9092
mp:
  messaging:
    outgoing:
      file.events:
        bootstrap:
          servers: localhost:9092